In [2]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [5]:
from tensorflow.keras.preprocessing.text import one_hot


In [11]:
## sentences

sent = ['the glass of milk',
        'the glass of juice',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words'
        'your videos are good',
        'I am happy to meet you',
        'we will win the match',
        'congratulations',
        'I am very happy to meet you',
        'good morning',
        'good afternoon',
        'good night',
        'take care'
        ]
## tokenizing the text


In [12]:
sent

['the glass of milk',
 'the glass of juice',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of wordsyour videos are good',
 'I am happy to meet you',
 'we will win the match',
 'congratulations',
 'I am very happy to meet you',
 'good morning',
 'good afternoon',
 'good night',
 'take care']

In [13]:
## define the vocabulary size

voc_size = 10000  # Size of the vocabulary

In [14]:
## one hot representation

one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

    

[[6059, 2255, 1240, 9325],
 [6059, 2255, 1240, 9536],
 [1628, 5445, 1442, 5377, 2395],
 [1628, 5445, 1442, 5377, 7699],
 [7472, 6059, 5558, 1240, 7136, 1073, 5874, 5377],
 [1628, 5445, 4399, 9446, 4913, 831],
 [7251, 3712, 6409, 6059, 4815],
 [867],
 [1628, 5445, 3880, 4399, 9446, 4913, 831],
 [5377, 7431],
 [5377, 8476],
 [5377, 6326],
 [901, 577]]

In [16]:
## word embedding representation 

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [21]:
import numpy as np

# Define the sentence length
sent_length = 8

# Pad the sequences
embedded_docs = pad_sequences(one_hot_repr, padding="pre", maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6059 2255 1240 9325]
 [   0    0    0    0 6059 2255 1240 9536]
 [   0    0    0 1628 5445 1442 5377 2395]
 [   0    0    0 1628 5445 1442 5377 7699]
 [7472 6059 5558 1240 7136 1073 5874 5377]
 [   0    0 1628 5445 4399 9446 4913  831]
 [   0    0    0 7251 3712 6409 6059 4815]
 [   0    0    0    0    0    0    0  867]
 [   0 1628 5445 3880 4399 9446 4913  831]
 [   0    0    0    0    0    0 5377 7431]
 [   0    0    0    0    0    0 5377 8476]
 [   0    0    0    0    0    0 5377 6326]
 [   0    0    0    0    0    0  901  577]]


In [22]:
## feature reprensetation 

dim=10




In [24]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

In [26]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 165ms/step


array([[[ 0.0356588 ,  0.0167574 ,  0.03583143, ...,  0.03277091,
          0.04411009, -0.0162045 ],
        [ 0.0356588 ,  0.0167574 ,  0.03583143, ...,  0.03277091,
          0.04411009, -0.0162045 ],
        [ 0.0356588 ,  0.0167574 ,  0.03583143, ...,  0.03277091,
          0.04411009, -0.0162045 ],
        ...,
        [ 0.03849589,  0.04152152, -0.03089981, ..., -0.02386524,
         -0.01829695, -0.00876785],
        [-0.00696965,  0.00405099,  0.02740857, ..., -0.00615442,
          0.02370243,  0.03255517],
        [-0.00801301,  0.04869467, -0.03142454, ..., -0.01963503,
          0.03169194, -0.04140123]],

       [[ 0.0356588 ,  0.0167574 ,  0.03583143, ...,  0.03277091,
          0.04411009, -0.0162045 ],
        [ 0.0356588 ,  0.0167574 ,  0.03583143, ...,  0.03277091,
          0.04411009, -0.0162045 ],
        [ 0.0356588 ,  0.0167574 ,  0.03583143, ...,  0.03277091,
          0.04411009, -0.0162045 ],
        ...,
        [ 0.03849589,  0.04152152, -0.03089981, ..., -

In [29]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 68ms/step


array([[ 0.0356588 ,  0.0167574 ,  0.03583143, -0.03883969, -0.02113189,
         0.00972845, -0.00051294,  0.03277091,  0.04411009, -0.0162045 ],
       [ 0.0356588 ,  0.0167574 ,  0.03583143, -0.03883969, -0.02113189,
         0.00972845, -0.00051294,  0.03277091,  0.04411009, -0.0162045 ],
       [ 0.0356588 ,  0.0167574 ,  0.03583143, -0.03883969, -0.02113189,
         0.00972845, -0.00051294,  0.03277091,  0.04411009, -0.0162045 ],
       [ 0.0356588 ,  0.0167574 ,  0.03583143, -0.03883969, -0.02113189,
         0.00972845, -0.00051294,  0.03277091,  0.04411009, -0.0162045 ],
       [ 0.00888293,  0.03326981, -0.00252578, -0.04143484,  0.03356104,
         0.03985142,  0.0023034 , -0.03724376, -0.01806681, -0.03775024],
       [ 0.03849589,  0.04152152, -0.03089981, -0.04967019,  0.0138202 ,
         0.03186036, -0.02163546, -0.02386524, -0.01829695, -0.00876785],
       [-0.00696965,  0.00405099,  0.02740857,  0.02568979, -0.01956254,
         0.01768227,  0.00169414, -0.00615442